### ISSUE TITLE
UnityEngine.CoreModule.dll access denied

### ISSUE THREAD

**Issue by Botond24** [nike4613/BeatSaber-IPA-Reloaded#17]
Whenever I launch IPA it says System.UnauthorizedAccessException: Access to the path 'common\Beat Saber\Beat Saber_Data\Managed\UnityEngine.CoreModule.dll' is denied.

**Comment by Botond24** [comment]
Beat Saber version: 1.1.0
Computer: Asus ROG G752VS
OS: Windows 10 Pro

**Comment by nike4613** [comment]
Usually when that happens it is due to one of:
- Windows being stupid and not fully closing the handle
- Beat Saber being open

Usually even just running the installer again fixes it. Failing that, fix your permissions.

**Comment by Botond24** [comment]
What do you mean by fix your permissions?

**Comment by Botond24** [comment]
I fixed my permissions but it still doesn't seem to work.
Neither on 1.1.0 nor 1.1.0p1
