### ISSUE TITLE
 Could not load file or assembly '0Harmony, Version=1.2.0.1, Culture=neutral, PublicKeyToken=null' or one of its dependencies.  File name: '0Harmony, Version=1.2.0.1, Culture=neutral, PublicKeyToken=null'

### ISSUE THREAD

**Issue by jiangdl** [nike4613/BeatSaber-IPA-Reloaded#22]
anyone help me? when run bs out log is :

Doorstop started!
DLL Path: C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\WINHTTP.dll
Doorstop DLL Name: WINHTTP
Looking for original DLL from C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\WINHTTP_alt.dll
Looking for original DLL from C:\WINDOWS\system32\WINHTTP.dll
Doorstop enabled!
Installing IAT hook
Hook installed!
Attempting to install GetMessageA and GetMessageW hooks
Could not hook GetMessageW! (not an error)
Attempting to install PeekMessageA and PeekMessageW hooks
Got mono.dll at 00007FFBD9A30000
Loading assembly: Beat Saber_Data/Managed/IPA.Injector.dll
Invoking method!
An error occurred invoking the injector: System.IO.FileNotFoundException: Could not load file or assembly '0Harmony, Version=1.2.0.1, Culture=neutral, PublicKeyToken=null' or one of its dependencies.

File name: '0Harmony, Version=1.2.0.1, Culture=neutral, PublicKeyToken=null'

**Comment by nike4613** [comment]
Is this an error you're getting from a custom verbose build?
Are you copying the entire output from the meta project?

**Comment by jiangdl** [comment]
This is the whole file. It ok when I would copy 0Harmony.dll into the steamapps/common/Beat Saber/Beat Saber_Data/Managed/.

**Comment by nike4613** [comment]
BSIPA by default doesn't output that log. Where are you getting your build of BSIPA?

**Comment by jiangdl** [comment]
I compiled it through source code

**Comment by nike4613** [comment]
Harmony should appear in the `Libs` folder of the output, did it not?

**Comment by nike4613** [comment]
Closed for lack of updates.

**Comment by windows10useryt** [comment]
uhh i had the same issue with cameraplus i needed harmony 1.2.0
