### ISSUE TITLE
A way for an IDisablablePlugin to signal it finished disabling itself

### ISSUE THREAD

**Issue by Zingabopp** [nike4613/BeatSaber-IPA-Reloaded#24]
It would be nice for the mods that need some time to clean up before they're disabled to have a way of signalling when they're finished. Mostly to make the Enable button in ModList inactive until the mod is finished.

**Comment by nike4613** [comment]
BSIPA 4's system will allow disable methods to return a `Task` that will be used to wait for completion. You will be able to use a [TaskCompletionSource<T>](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskcompletionsource-1?view=netframework-4.8) to provide that if you aren't using tasks already.

**Comment by nike4613** [comment]
See above. BSIPA 4 is now merged.
