### ISSUE TITLE
BSIPA Install Access refused

### ISSUE THREAD

**Issue by TheStaticTurtle** [nike4613/BeatSaber-IPA-Reloaded#25]
I wanted to patch beatsaber 1.3 but the ipa.exe installer refuse ton Install due to an System.UnauthorizeAccessExecption while backuping the System.Runtime.Serialization. It can't seems to works even after a reboot and throws out the same error even in while lainchin in administrator. i've try to patch in a cm to test but non luck. So it isn't a permission issue. If you need the full log

**Comment by nike4613** [comment]
I mean, it's definitely either a permissions issue or you just have the game running. Make sure the game is closed when you install, and try setting the install dir to have world read/write.

**Comment by TheStaticTurtle** [comment]
I mean how could it be a permission issue when it's not even running on differents machines this dosen't make any sense. Could steam be using the dll even when the game wasn't started?

**Comment by nike4613** [comment]
Windows/steam sometimes fucks up permissions so that you don't actually have access to, say, write files when you should. Its a lot more common than you'd think.

**Comment by TheStaticTurtle** [comment]
So how would you fix it because I 've already tried to set permission in windows and that still dosen't explain why it's not working on linux

**Comment by nike4613** [comment]
Oh, are you on Linux?

In that case, its more likely that the installer is just buggy. If you look around a little bit, there have been a number of people that are working and happy on Linux, so you'd probably be better off asking them. 

If its on Windows, make *absolutely certain* that no BS process is running, and make sure your user has full write permissions on the entire installation folder, and try again.

**Comment by TheStaticTurtle** [comment]
No I am on windows and just for the try I switch to linux and it's the exact same error so it doesn't make sense and I already try to manually set permission recursively in the bs folder to ensure all right and I can move the dll my self just IPA who doesn't work are you sure that it couldn't be something else ?

**Comment by nike4613** [comment]
Not with a permission error, no. You should probably head over to #pc-mod-support in the discord, I know they know how to fix it

**Comment by geefr** [comment]
@TurtleForGaming best to keep this discuss focused on windows, for Linux I doubt it's the same error even if the output is similar.
(Go here for Linux, there are several other bugs to work aroun : https://github.com/geefr/beatsaber-linux-goodies)

On windows there's several thibgs that can prevent a file from being written, even if you have permissions:
- try moving the steam library to another drive, or somewhere that is not in program files
- tools such as 'unlocker' can tell you if a process is using the file
- sometimes windows permissions break randomly and prevent even admins changing a file, no idea why but I frequently encounter this one..

**Comment by TheStaticTurtle** [comment]
Thanks turn's out the the file was in readonly I almost missed it thanks.
