### ISSUE TITLE
[Mod List/Updater] New dependencies are not downloaded on update for mod with invalid id/name

### ISSUE THREAD

**Issue by brian91292** [nike4613/BeatSaber-IPA-Reloaded#28]
As noted in the title, a mod with an invalid id/name will be updated properly (I assume based on hash or something), however any new dependencies associated with it will *not* be downloaded. 

Example:
The old YUR.fit mod had an invalid manifest. The id/name said "YUR" when the name on BeatMods is "YUR Fit Calorie Tracker". The BSIPA mod list properly identifies that the mod has an update, and updates it accordingly, however it does not download the new dependencies (BeatSaberMarkupLanguage and SkiaSharp).

I've been told this might be happening due to the invalid name/id in the manifest, but if that is the case then BSIPA should not be downloading an update for this mod in the first place, or it should correctly identify the new dependencies and download them accordingly. Therefore, I assume this is a bug in the updater logic.

Let me know if you need me to provide any more details.

**Comment by brian91292** [comment]
[2019.12.12.10.03.19.log](https://github.com/beat-saber-modding-group/BeatSaber-IPA-Reloaded/files/3957193/2019.12.12.10.03.19.log)

**Comment by nike4613** [comment]
(Putting this here too for later reference)

It does not fall back to hash. I believe the only reason it works at all is because BeatMods does fuzzy matching to some extent, and I don't believe there is an endpoint that doesn't, so the ID was evidently close enough to work. Not sure why it isn't downloading the dependencies properly though.

**Comment by nike4613** [comment]
This seems to be a BeatMods issue (as per usual).

**Comment by brian91292** [comment]
Can't say I'm surprised- thanks for looking into it.
