### ISSUE TITLE
Unable to load Mod, the following error is displayed after adding --verbose

### ISSUE THREAD

**Issue by WGzeyu** [nike4613/BeatSaber-IPA-Reloaded#36]
I'm in Beat Saber 1.7.0, which is newly installed and has been run once,
BSIPA 3.13.7 was installed using ModAssistant, but the Mod option cannot be loaded anyway.
When I opened `Beat Saber\Plugins`, I couldn't find any mods.
After running the Beat Saber with the --verbose parameter, BSIPA outputs the following:

> System.ArgumentException: Value does not fall within the expected range.
  at IPA.Loader.LibLoader+<TraverseTree>d__13.MoveNext () [0x00061] in <561f7537f11b496bb2465f41d54f54b0>:0
  at IPA.Loader.LibLoader.SetupAssemblyFilenames (System.Boolean force) [0x0009d] in <561f7537f11b496bb2465f41d54f54b0>:0
  at IPA.Loader.LibLoader.Configure () [0x0002c] in <561f7537f11b496bb2465f41d54f54b0>:0
  at IPA.Injector.Injector.SetupLibraryLoading () [0x0000e] in <be115a6bb98644f2a26a8cc4a1537f7b>:0
  at IPA.Injector.Injector.Main (System.String[] args) [0x00017] in <be115a6bb98644f2a26a8cc4a1537f7b>:0
Setting breakpad minidump AppID = 620980
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198430065093 [API loaded no]

![](https://wgzeyu.gtxcn.com/img/TIM%E5%9B%BE%E7%89%8720200306025228.png)

This is the game's log folder:
[https://wgzeyu.gtxcn.com/img/Logs.zip](https://wgzeyu.gtxcn.com/img/Logs.zip)

**Comment by WGzeyu** [comment]
When using Beat Saber 1.6.0 (I remember it should be January 7th), the mod can still load normally. But I forgot the version of BSIPA when I installed Mod.

**Comment by nike4613** [comment]
It looks to me like you somehow don't have a `Libs` folder in your installation. The BSIPA installer should ensure that it exists when it is run, though it seems like it somehow got removed on your installation.

On another, note, I noticed that you are running with a Chinese locale, which is known to cause issues with time on Mono, the runtime that the game uses. That is why the name of the log files is so broken, as it is simply using a monotonically increasing counter.

**Comment by WGzeyu** [comment]
I have tried multiple clean installations and exited the antivirus software, and it didn't work. 
So I think it should not be a missing file.

**Comment by nike4613** [comment]
Can you upload a screenshot of your installation directory?

**Comment by WGzeyu** [comment]
![](https://wgzeyu.gtxcn.com/img/TIM%E5%9B%BE%E7%89%8720200309050738.png)
![](https://wgzeyu.gtxcn.com/img/TIM%E5%9B%BE%E7%89%8720200309050751.png)
![](https://wgzeyu.gtxcn.com/img/TIM%E5%9B%BE%E7%89%8720200309050755.png)

**Comment by nike4613** [comment]
As I said before, you are missing `Libs` in the root installation directory. The IPA installer should copy the files in `IPA/Libs` out for use by the game.

**Comment by WGzeyu** [comment]
Just tried manually copying `IPA\Pending` and `IPA\Libs` to the game root directory, but it still doesn't work
![](https://wgzeyu.gtxcn.com/img/TIM%E5%9B%BE%E7%89%8720200309065826.jpg)
![](https://wgzeyu.gtxcn.com/img/TIM%E5%9B%BE%E7%89%8720200309065920.jpg)
![](https://wgzeyu.gtxcn.com/img/TIM%E5%9B%BE%E7%89%8720200309065924.jpg)

**Comment by nike4613** [comment]
Are there any errors in the console or log files?

**Comment by WGzeyu** [comment]
[https://wgzeyu.gtxcn.com/img/log2.zip](https://wgzeyu.gtxcn.com/img/log2.zip)
![](https://wgzeyu.gtxcn.com/img/TIM%E6%88%AA%E5%9B%BE20200309140916.png)

**Comment by nike4613** [comment]
Aha. Yeah, that looks like a side effect of the locale issue I mentioned before. Try running the game through NTLEA or changing your Windows locale to something that isn't Chinese.

**Comment by WGzeyu** [comment]
I didn't think it was a problem caused by the locale or language setting before, in fact I was helping a friend to feedback the problem.
I myself use the exact same locale and language settings (Simplified Chinese, China) and have not encountered any problems.
I just asked him to try to change the control panel and Win10 settings and system language to English (UK), then start the game directly, there is still no Mod.
However, at this time, after reinstalling Mod using ModAssistant in English environment, everything works.
After that he changed the system language and region to Simplified Chinese (China), and Mod still works.

**Comment by nike4613** [comment]
At some level, that doesn't actually surprise me...

I was playing with it in a VM a bit ago, and after installing the Simplified Chinese language pack and setting that as the system locale, it still worked fine, so I suspect that simply having the English language pack installed is enough to make it work.

Needs more testing, but I don't particularly care to get my hands on a Chinese install disk for Windows. If you or someone else wants to investigate further, I'd ask you to open another issue to track it.
