### ISSUE TITLE
Refs/refs.txt - Build failure report

### ISSUE THREAD

**Issue by ghost** [nike4613/BeatSaber-IPA-Reloaded#37]
This is merely a report for notification, just in case it is helpful.

1. The issue
    - When building for .NET 4, build fails because there is no Muse Dash.
1. Versions
    - BSIPA 4.0.0-beta branch
    - Beat Saber 1.8.0b1 Beta branch, but other versions should apply.
1. Steps to reproduce:
    - Cloned the repo
        ```sh
        git clone repo && cd repo
        git checkout 4.0.0-beta
        git submodule init && git submodule update
        ```
    - Made the `bsinstalldir.txt` directory with the appropriate path
    - Opened the solution in Visual Studio and Build Debug - x64-Net4.
    - Build fails with:
      `"$"Invalid PathMuseDash_Data/Managed/UnityEngine.CoreModule.dll?alias=UnityEngine.CoreModule.Net3.dll" System.ArgumentException: Invalid character in path (refs.txt:45 or refs.txt:46)`
    - The above can be solved by getting rid of the Muse Dash part in `refs.txt`.
    - Additionally, for Beat Saber 1.8.0b1, build also fails with:  
      `System.IO.FileNotFoundException: 'C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Beat Saber_Data/Managed/MainAssembly.dll' File not found. (refs.txt:34)`
    - This can also be solved by adding `"""Main.dll?virt` at the last Beat Saber option in `refs.txt`
    - Also, BSIPA-ModList doesn't build at all with a bunch of missing references, thus needs to be disabled.

Pretty sure it's a known issue, pinging just in case it needs to be taken care of.
Thank you for reading.

**Comment by nike4613** [comment]
The 4.0.0-beta branch is outdated. The latest development is occurring on master. 

The MuseDash info is (or should be) in an optional block, and should cause no issues.

ModList has been disabled from solution builds for a number of updates, as it has not been updated since BSML was adopted.
