### ISSUE TITLE
Corrupted All Of The Game Files

### ISSUE THREAD

**Issue by TexanszYT** [nike4613/BeatSaber-IPA-Reloaded#45]
WTH i get this from beatsaver and i click it and everything is gone off of my computer and will not open it saying major files are corrupted.  Frick This!!!

**Comment by TexanszYT** [comment]
╭∩╮( ͡° ل͟ ͡° )╭∩╮

**Comment by nike4613** [comment]
You most likely downloaded a virus, and not the actual application. The only places that you should get BSIPA are this repo's releases section and beatmods.com
