### ISSUE TITLE
[Request] Commandline argument to show BSPIA version

### ISSUE THREAD

**Issue by laundmo** [nike4613/BeatSaber-IPA-Reloaded#52]
its very common for applications to be able to show their isntalled version using a commandline flag

i suggest `IPA.exe -v` and/or `IPA.exe --version`

**Comment by nike4613** [comment]
`IPA.exe -v` is implemented. (See https://bsmg.github.io/BeatSaber-IPA-Reloaded/articles/command-line.html?tabs=installer).
