### ISSUE TITLE
Build fail on path with space, works otherwise

### ISSUE THREAD

**Issue by danielocdh** [nike4613/BeatSaber-IPA-Reloaded#56]
So after many tries I figured out the problem was one space on my path.
It works with `projects\Beat_Saber\BeatSaber-IPA-Reloaded`
It didn't work with `projects\Beat Saber\BeatSaber-IPA-Reloaded`

tested on 9cb44d8d8466965d589b616f0507b011e8663ae6

**Comment by nike4613** [comment]
What errors were you getting?

**Comment by danielocdh** [comment]
> What errors were you getting?

Sorry, I assumed this was happening everywhere and was very easy to reproduce, tried it again just now with `projects\Beat Saber`

- Windows 10 1909 fully updated
- Visual Studio 2019 16.7.7
- MSVC v142 - VS 2019 C++ x64/x86 build tools (v14.27)
- .NET 4.6.1 SDK and .NET 4.7.2 SDK downloaded/updated the day I opened this issue
- Beat Saber v1.12.2

The error:
`Error	MSB3073	The command "C:\Users\xxx\Desktop\projects\Beat Saber\BeatSaber-IPA-Reloaded\Doorstop\BuildUtils\ducible.exe C:\Users\xxx\Desktop\projects\Beat Saber\BeatSaber-IPA-Reloaded\Doorstop\Proxy\bin\x64\Release\Proxy.dll C:\Users\xxx\Desktop\projects\Beat Saber\BeatSaber-IPA-Reloaded\Doorstop\Proxy\bin\x64\Release\Proxy.pdb" exited with code 9009.	proxy	C:\Users\xxx\Desktop\projects\Beat Saber\BeatSaber-IPA-Reloaded\Doorstop\Proxy\Proxy.vcxproj	188`

If it is hard to fix or only happening on specific configurations, might be best to just add a note in the building docs about having spaces on the path
