### ISSUE TITLE
Game unable to launch unless cleaninstall is performed

### ISSUE THREAD

**Issue by megalon** [nike4613/BeatSaber-IPA-Reloaded#6]
We have had several users in the #support channel report that when they launch the game they briefly see a console window, then the game closes. Here is an example https://cdn.discordapp.com/attachments/442696229508612096/564336479833292810/bandicam_2019-04-06_23-26-34-710.jpg

Here is the output log of the user above
[output_log.txt](https://github.com/nike4613/BeatSaber-IPA-Reloaded/files/3051262/output_log.txt)

**Workaround**
Currently the solution is to perform a clean reinstall of Beat Saber with the following steps
1. Make sure to back up your CustomSongs folder before uninstalling
2. Uninstall Beat Saber
3. Delete your "Beat Saber" folder
4. Reinstall the game, then make sure to run it once without modding it, then close it
5. Mod the game using the latest Mod Manager https://github.com/beat-saber-modding-group/BeatSaberModInstaller/releases/latest

**Comment by nike4613** [comment]
From what I can tell, this seems to be an issue with Unity, seeing all the symbol resolution errors in the output log. I would *imagine* that a simple verify integrity would work just fine, purely based on the output log. If you run into any more instances of this happening, could you have them send the crash log from `%APPDATA%\..\Local\Temp\Hyperbolic Magnetism\Beat Saber\Crashes`? Not sure I can do anything about this though.

**Comment by megalon** [comment]
I found one user with this issue that had no crash logs (great), but I did find another user that had crash logs.

This user actually isn't able to launch the game, even after performing a clean install.
`Hachumi#7498` on Discord

[Crash_2019-04-11_192123577.zip](https://github.com/nike4613/BeatSaber-IPA-Reloaded/files/3070313/Crash_2019-04-11_192123577.zip)

**Comment by nike4613** [comment]
Those 2 users seem to have completely different errors. The first seems to be a case where Unity failed to register internal calls or something, where the latter is a case of an access violation in  `vrclient_x64.dll`. For him, try updating SteamVR. Still no idea about the first one.

**Comment by nike4613** [comment]
Has this issue been confirmed on 3.12.12?

**Comment by megalon** [comment]
I haven't seen anyone with this exact issue (where the console window appears, then closes and the game doesn't launch) but we are still seeing users who's game will crash on launch and show the Unity crash window with the green progress bar, like this
https://cdn.discordapp.com/attachments/442696229508612096/568643301977227275/Screenshot_12.png
This message from yesterday
https://discordapp.com/channels/441805394323439646/442696229508612096/568643206871384074

And this one, also from yesterday
https://discordapp.com/channels/441805394323439646/442696229508612096/568541270474227732
I found both of those by just searching for "crash" in #support

Clean installs seem to work for most of these users. 
I can ask support to keep an eye out for users whose games are crashing like this, and try to get more log files. Would you like that in a different issue instead of this one?

**Comment by nike4613** [comment]
It still fits in this issue's title, so just drop them here.

**Comment by Vaxela** [comment]
Hey i have the same issue i install mods and my game crash and doesn't launch

**Comment by nike4613** [comment]
No issue bumps in several updates, and I haven't seen this issue recently, so calling it fixed.
