### ISSUE TITLE
System.NullReferenceException on game start in System.Guid.NewGuid()

### ISSUE THREAD

**Issue by rogerx333** [nike4613/BeatSaber-IPA-Reloaded#60]
![Desktop Screenshot 2021 02 03 - 17 37 58 54](https://user-images.githubusercontent.com/78512153/106820850-1623f380-664a-11eb-97c5-9bac0e2053b2.png)

**Comment by nike4613** [comment]
Just making sure: you have asked about this in #pc-help in the Discord, verified the integrity of your game files, etc. already?

**Comment by rogerx333** [comment]
Yes I have

**Comment by nike4613** [comment]
Alright, I'm going to ask you to first reboot your computer, and if that doesn't fix it, run [the executable in this ZIP file](https://github.com/bsmg/BeatSaber-IPA-Reloaded/files/5923189/TestCrypto.zip) in a command prompt and send its output.

**Comment by nike4613** [comment]
This was eventually resolved by reinstalling Windows. Somehow, Windows' Crypto library was failing to initialize for Beat Saber.
