### ISSUE TITLE
Getting an error message with no text after loading IPA

### ISSUE THREAD

**Issue by Stereotype12** [nike4613/BeatSaber-IPA-Reloaded#61]
![sure](https://user-images.githubusercontent.com/71988508/109423937-1f815100-79a7-11eb-986c-e6f966e1e7a4.png)
This happens after I load mods and the IPA, no idea why this is happening.

**Comment by nike4613** [comment]
That (I think?) means your Windows is even more fucked than the guy in #60. Having looked through your message history in the discord, it looks like you were having the same issue as #60 a few weeks ago, and the only known solution to that is a Windows reinstall.

**Comment by Stereotype12** [comment]
> That (I think?) means your Windows is even more fucked than the guy in #60. Having looked through your message history in the discord, it looks like you were having the same issue as #60 a few weeks ago, and the only known solution to that is a Windows reinstall.

Hm, alright, sucks I have to do a clean reinstall but whatever I have to do to get this working again.
