### ISSUE TITLE
Game crashes when launching from executable without SteamVR

### ISSUE THREAD

**Issue by andriygm** [nike4613/BeatSaber-IPA-Reloaded#70]
When launching the game through its executable (Beat Saber.exe) or through a shortcut (e.g. in an Oculus library) with BSIPA installed, the game crashes with the following "Sharing violation on path" error. The game launches through these shortcuts correctly without BSIPA.

![image](https://user-images.githubusercontent.com/7087461/128416572-eb867bb2-05f1-4318-aeb7-382d58a8bfb9.png)

**Comment by nike4613** [comment]
That error is unrelated to launching through a shortcut. It generally happens when you started the game multiple times, or something similar. If you can *reliably* reproduce it when the game is only launched once, then please create another issue with a description of that reproduction.
