### ISSUE TITLE
Game crashes when launching from executable without SteamVR

### ISSUE THREAD

**Issue by andriygm** [nike4613/BeatSaber-IPA-Reloaded#71]
(This is a reopening of #70, addressing the original comment)

When launching the game through its executable (Beat Saber.exe) or through a shortcut (e.g. in an Oculus library) with BSIPA installed, the game crashes with the following "Sharing violation on path" error. The game launches through these shortcuts correctly without BSIPA. The error occurs regardless of number of launch attempts, and can be recreated as follows:

1. Reboot computer.
2. Connect a virtual reality device (I use the Oculus Quest 2 via Air Link, have not tested with other headsets or connection methods).
3. Launch Steam.
4. Launch Beat Saber by navigating to game data folder and running Beat Saber.exe (tested with the default mods on 1.16.4 via Mod Assistant, as well as only BSIPA, SongCore, and corequisites).

This procedure has been tested multiple times, with a consistent crash message result.

![image](https://user-images.githubusercontent.com/7087461/128416572-eb867bb2-05f1-4318-aeb7-382d58a8bfb9.png)

**Comment by nike4613** [comment]
Have you considered launching through Steam, like it forces? I can't say I'm all that surprised that launching the game directly doesn't work with the Steam installation. There's also not a whole lot that can be done about this, short of hijacking the relaunch process, and I'm not a fan of that.

**Comment by nike4613** [comment]
Also, I would have rathered you just comment on the already closed issue. I can reopen if necessary.

**Comment by scott28280** [comment]
I am getting a similar error while launching from both steam client and inside steam VR, only occurs when bsipa 4.2.0 is installed.
![Capture](https://user-images.githubusercontent.com/91920403/135931917-71c9ade1-f01b-44f8-9030-3a05f4e01737.PNG)

**Comment by nike4613** [comment]
> I am getting a similar error while launching from both steam client and inside steam VR, only occurs when bsipa 4.2.0 is installed. ![Capture](https://user-images.githubusercontent.com/91920403/135931917-71c9ade1-f01b-44f8-9030-3a05f4e01737.PNG)

That is, in fact, a completely unrelated issue related to an old installation. If you'd asked in  #pc-help in the BSMG discord, they would have told you exactly how to fix it: delete `0Harmony.dll` and reinstall.
