### ISSUE TITLE
Unable to find package `Hive.Versioning.Standalone`.

### ISSUE THREAD

**Issue by valkjsaaa** [nike4613/BeatSaber-IPA-Reloaded#77]
I got this error when trying to build this project. I have followed the instructions in the [guide](https://bsmg.github.io/BeatSaber-IPA-Reloaded/articles/contributing.html).

I also cannot find `Hive.Versioning.Standalone` NuGet package anywhere on web.

Thanks in advance!

**Comment by nike4613** [comment]
`Hive.Versioning` is a part of the larger `Hive` project, which, while incomplete, is still far superior to other options. At the moment, it is available on GitHub Packages [here](https://github.com/orgs/Atlas-Rhythm/packages?repo_name=Hive), and documentation on using it is available [here](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-nuget-registry).

In all likelihood, I will not update the documentation, as in the relatively near future we intend to publish `Hive.Versioning` and related packages on NuGet.org. 

I will close this issue once that happens.

**Comment by valkjsaaa** [comment]
This is very helpful. Thanks!

**Comment by valkjsaaa** [comment]
One more thing. I'm planning to use BSIPA to mod other Unity games. Are there any "gotcha"s that I should pay attention to?

I have tried to mod "Cooking Simulator VR" with BSIPA, but it seems that the game is not even loading my plugin (no mention of my plugin in the log). I suspect that BSIPA is checking the "gameVersion" against the game version although the documentation says BSIPA is not checking that currently. Any suggestions?

**Comment by nike4613** [comment]
I can't say I would recommend using BSIPA in other games, as it makes quite a lot of assumptions about which subset of .NET Standard the game is using which are not true in general. I would recommend using BepInEx for most games.

**Comment by valkjsaaa** [comment]
thanks a lot! BepInEx works for me!

**Comment by Gordin** [comment]
I'm running into the same problem as @valkjsaaa . I looked at the Hive Project and I couldn't find any Download for the Versioning Standalone lib, even though there is a Downloads counter? I tried the "Install from commandline" command `dotnet add package Hive.Versioning.Standalone --version 0.1.0-gh918.1`, but that just gives a not found error again. Do I really have to setup and build the whole Hive project just to get a SemVer library? :/

**Comment by Gordin** [comment]
OK, I think I figured it out... Creating a classic Personal Access token and running this command seems to work to add it to the sources, looks like the package can be found afterwards. (I'm not sure, as I still have a lot of other build errors...)
`dotnet nuget add source --username USERNAME --password GITHUB_CLASSIC_TOKEN --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Atlas-Rhythm/index.json"`

**Comment by shny-scott** [comment]
> in the relatively near future we intend to publish `Hive.Versioning` and related packages on NuGet.org.

Any update on this?
