### ISSUE TITLE
getThreadContext FAILED upon launching

### ISSUE THREAD

**Issue by JaViLuMa** [nike4613/BeatSaber-IPA-Reloaded#8]
The new IPA has been causing me and "many" others some problems upon launching the game. Some say the problem was FaceIT Anti cheat and upon deleting it, it worked for them. But I still have the same issue(s) even though I uninstalled FaceIT.

What I tried to fix the issue:

-Uninstall FaceIT
-Reinstalling the game
-Manually downloading ALL of the mods, including IPA (it worked like this, but when I tried launching the game second time, I got the same error(s) again
-Verifying game files

This is the first part I get: 

https://imgur.com/a/bqhJrnM

This is the second part:

https://imgur.com/a/Oo3aLiv

**Comment by nike4613** [comment]
There are several anticheats that seem to cause problems, as well as a few AVs. Do you have any other anticheat or antivirus installed?

**Comment by JaViLuMa** [comment]
I have ESEA AC for CSGO (I didn't have any problems with it before) and I have Windows Defender (didn't do anything on it since I activated my Windows).

**Comment by nike4613** [comment]
ESEA is one of the ones that are known for causing issues. I'll see if I can't figure it out. If there is a wat to completely disable ESEA without uninstalling, I reccommend you try that.

**Comment by nike4613** [comment]
Also make sure that DEP is set to "Windows programs and services only".
DEP is at 'Right click My Computer -> Properties -> Advanced System Settings -> "Advanced" tab -> Performance settings -> "Data Execution Prevention" tab'.

**Comment by JaViLuMa** [comment]
Will try disabling the ESEA in Firewall or something else. And I think by default my DEP is set to that

**Comment by JaViLuMa** [comment]
Hello.

2 days after I opened this issue I uninstalled ESEA. It worked. 
Day later I decided to install some Windows updates AND INSTALLED ESEA again since my friend wanted me to play with him ESEA. The game was ALSO working WITH ESEA INSTALLED.

2 days ago I get the same issue again as when I opened this git issue.

Updating windows seemed like it did do something, I tried that again but no luck this time.

**Comment by ColonelPanic-42** [comment]
Just to throw my 2 cents in, this is happening under Wine/Proton as well. There are no other games installed and no anti cheats installed. Not sure if that will mean anything

**Comment by nike4613** [comment]
Some occurrences of this error seem to be solved by verifying integrity of game cache, or reinstalling.

**Comment by Starbyte** [comment]
Same issue and still getting it, did a completely clean install of beat saber, all files validated successfully, launch the game, get the "GetThreadContext failed", 2-3 files fails failed to validate and will be reacquired. Rinse and repeat.

**Comment by nike4613** [comment]
This seems to have been resolved by Unity.
