### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by sebastientromp** [nike4613/BeatSaber-IPA-Reloaded#80]
Hello,

I am developing an app for another unity game, and was looking at including a way to meet users install mods for the game. Ideally, the app would include something like BSIPA and the users would only take care of the mods themselves.

I looked for a license file, but could not find it. 

Would you mind clarifying for the license for it is?

Thanks, and sorry if I missed the information somewhere.

**Comment by Meivyn** [comment]
Sorry but, you made me laugh. I'd like to know how you managed to miss that.

![image](https://user-images.githubusercontent.com/793322/159347014-b3a719fe-e8cc-46ee-bf83-4524918a1497.png)
![image](https://user-images.githubusercontent.com/793322/159347034-6f241453-63cf-414a-abcc-76c2acd73149.png)

BSIPA is MIT-licensed.

**Comment by sebastientromp** [comment]
Wow, I'm sorry... I just checked, and found my eyes had left their sockets.

Thanks a lot for having the patience to deal with this kind of questions :D
