### ISSUE TITLE
Rebuild GameAssemblies on game version change

### ISSUE THREAD

**Issue by Zingabopp** [nike4613/BeatSaber-IPA-Reloaded#81]
Seems a lot of people have been having problems this update with the `GameAssemblies` array in the config file being outdated. Rebuilding that array when a game version change is detected could solve that. Perhaps add a config option similar to `Yeetmods` to disable the behavior and only do it if IPA has a default list of game assemblies to set.

**Comment by Jake-Thomas-Hall** [comment]
#79 is an issue that I opened about this, describes the same problem as this.
