### ISSUE TITLE
Nullable DateTime converter clears data in json config file

### ISSUE THREAD

**Issue by IlinAleksey** [nike4613/BeatSaber-IPA-Reloaded#82]
Using `[UseConverter]` attribute for properties with type `DateTime?` causes strange behaviour when `GeneratedStore.Generated` function is called. Some date data in config file is reset to `null`, and what data exactly is reset to `null` is even more strange: only dates with even seconds, so value `"2022-03-23T18:33:43.0000000"` won't be reset, but `"2022-03-23T18:33:44.0000000"` will be.

I don't know if it's a BSIPA bug or I use these methods and attributes wrong, or there is some silly environment issue on my side. `[UseConverter]` for other types (`string`, `int`) works fine btw

Steps to reproduce:

- define class `SimpleStore`
```cs
    internal class SimpleStore
    {
        public static SimpleStore Instance { get; set; }

        [UseConverter]
        public virtual DateTime? Date { get; set; }
    }
```

- create file `SimpleStore.json` in `UserData` folder with contents
```json
{
  "Date": "2022-03-23T18:33:44.0000000"
}
```

- call `SimpleStore.Instance = Config.GetConfigFor("SimpleStore").Generated<Configuration.SimpleStore>();` in `InitWithConfig`

- build, launch game, don't even have to wait for the main menu to appear

- contents of `SimpleStore.json` is now
```json
{
  "Date": null
}
```

**Comment by nike4613** [comment]
Can I get a log file of this happening?

**Comment by IlinAleksey** [comment]
> Can I get a log file of this happening?

[20220409-1207.log](https://github.com/bsmg/BeatSaber-IPA-Reloaded/files/8456605/20220409-1207.log)

Log of the game launch
The plugin i am debugging is called "Song Browser"
