### ISSUE TITLE
--debug launch arg results in hard crash on Unity 2021.3.16f1

### ISSUE THREAD

**Issue by ErisApps** [nike4613/BeatSaber-IPA-Reloaded#90]
As the title implies, adding the `--debug` launch argument results in the Beat Saber hardcrashing immediately.

As part of the investigation regarding this issue, I've been able to conclude that options like `ShowDebug`, `ShowTrace` and `ShowCallSource` can be enabled in the BSIPA config file while not hardcrashing the game. I am however not sure whether the last option actually properly works though.

That all being said, based on this all... I'm currently taking a slightly educated guess that the issue lies in the doorstop proxy, more specifically around these lines below. I haven't been able to figure out just yet (due to my limited knowledge of C++) whether it would be caused by the `mono_debug_init` method call or the `mono_debug_domain_create` method which gets called at the end though.
https://github.com/nike4613/BeatSaber-IPA-Reloaded/blob/88424482b87d6a48af91a2db571876d1c73532b0/Doorstop/Proxy/main.c#L120-L133

Assuming the doorstop proxy is still partially based upon [UnityDoorstop-BSIPA](https://github.com/nike4613/UnityDoorstop-BSIPA) which is most likely based upon an earlier version of [UnityDoorstop](https://github.com/NeighTools/UnityDoorstop
), it might be worth considering moving towards a more up-to-date version of doorstop.

Relevant info:
- BS 1.29.4 on Steam
- Unity 2021.3.16f1
- [SteamVR Beta 1.26.2](https://store.steampowered.com/news/app/250820/view/3696935361531253499)
- Windows 10 21H2

_I'll try to attach a native crash log if I can get one._

**Comment by ErisApps** [comment]
Native crashlog kindly provided by @Kevman95
[Player.log](https://github.com/nike4613/BeatSaber-IPA-Reloaded/files/11441086/Player.log)

Looking at the stacktrace though, it's most likely caused by the `mono_debug_init` method call.

**Comment by MatrikMoon** [comment]
I notice the Doorstop version we're using is quite out of date. Could this be related to that?

EDIT: Seems not! I missed the associated PR. Nice work, smart folks ❤️

**Comment by ErisApps** [comment]
Closing the issue as it should be resolved by the linked PR.
